### ISSUE TITLE
In the notebook baselines/EntropicNeuralOptimalTransport/notebooks/High_dimensionsal_gaussians.ipynb, I believe that the closed form formula for the EOT plan between Gaussians is wrong.

### ISSUE THREAD

**Issue by theouscidda6** [ngushchin/EntropicOTBenchmark#4]
In the EntropicOTBenchmark/baselines/EntropicNeuralOptimalTransport/notebooks/High_dimensionsal_gaussians.ipynb, I believe that the closed formula entropic optimal transport plan (EOT) between Gaussians measures is not correct.
It does not coincide with that proved in [Janati+2020] and coded in https://github.com/hichamjanati/Entropic-OT-gaussians/blob/master/closed_forms.py, see function ``closed_form_balanced``.

Indeed, [Janati+2020] states that for $\mu = \mathcal{N}(0, \mathbf{A})$ and $\nu = \mathcal{N}(0, \mathbf{B})$ (which is used in the notebook), if we set $\varepsilon = 2 \sigma^2$ then $\pi^\star_\varepsilon$ reads:

$$
\pi_\varepsilon^\star \sim \mathcal{N}(0, \begin{bmatrix}
A & C_\sigma \\
C_\sigma^T & B
\end{bmatrix})
$$

where $C_\sigma= \tfrac{1}{2} (\mathbf{A}^{1/2} D_\sigma \mathbf{A}^{- 1/2} - \sigma^2 \mathbf{I}\_d)$ with $D_\sigma = (4 \mathbf{A}^{1/2} \mathbf{B} \mathbf{A}^{1/2} + \sigma^4 \mathbf{I}\_d)^{1/2}$.

In cell ``[26]`` of Sec. 4 of the High_dimensionsal_gaussians.ipynb notebook, there seems to be an error in the variable change $\varepsilon = 2\sigma^2$. Indeed,
- the functions ``get_D_sigma`` returns ``0.5*(covariance_0_sqrt@D_sigma@covariance_0_sqrt_inv - epsilon*np.eye(shape))``.
- the functions ``get_C_sigma`` returns``symmetrize(sqrtm(4*covariance_0_sqrt@covariance_T@covariance_0_sqrt + (epsilon**2)*np.eye(shape)))``.

However, if we rewrite $C_\sigma$ and $D_\sigma$ with $\sigma = \sqrt{\varepsilon /2}$, we then get: 
- $D_\sigma = (4 \mathbf{A}^{1/2} \mathbf{B} \mathbf{A}^{1/2} + \tfrac{1}{4}\varepsilon^2 \mathbf{I}\_d)^{1/2}$.
- $C_\sigma= \tfrac{1}{2} (\mathbf{A}^{1/2} D_\sigma \mathbf{A}^{- 1/2} - \tfrac{1}{2}\varepsilon \mathbf{I}\_d)$ .

Therefore, ``epsilon**2`` in ``get_D_sigma`` should be replaced by ``epsilon**2/4``; and ``epsilon**2`` in ``get_C_sigma`` should be replaced by ``epsilon / 2``; i.e.
- the functions get_D_sigma should instead return ``0.5*(covariance_0_sqrt@D_sigma@covariance_0_sqrt_inv - (epsilon / 2) *np.eye(shape))``.
- the functions get_C_sigma should instead return ``symmetrize(sqrtm(4*covariance_0_sqrt@covariance_T@covariance_0_sqrt + ((epsilon**2 / 4)*np.eye(shape)))``.

This is a crucial problem because the way functions are currently coded results in the covariance matrix
 
$$
\begin{bmatrix}
A & C_\sigma \\
C_\sigma^T & B
\end{bmatrix}
$$

to have significantly negative eigenvalues.

**Comment by ngushchin** [comment]
Hello, thank you for your interest in our work.

First of all, please note that the notebook EntropicOTBenchmark/baselines/EntropicNeuralOptimalTransport/notebooks/High_dimensionsal_gaussians.ipynb is from the folder baselines/EntropicNeuralOptimalTransport, which contains the code for one of the methods we evaluated in our work. But this folder also contains code for other experiments from the corresponding paper "Entropic Neural Optimal Transport via diffusion process" (https://neurips.cc/virtual/2023/oral/73836). In particular, the code from High_dimensionsal_gaussians.ipynb was not used for the Entropic OT benchmark.

Second, in our work we consider the entropic OT problem in the form:

$$
\min\_{\pi \in \Pi(\mathbb{P}\_0, \mathbb{P}\_1)} \int \frac{||x-y||^2}{2} d\pi(x,y) - \epsilon H(\pi),
$$

where $H(\pi)$ is the differential entropy of the distribution $\pi$. This problem is equivalent to the problem:

$$
\min\_{\pi \in \Pi(\mathbb{P}\_0, \mathbb{P}\_1)} \int \frac{||x-y||^2}{2}  d\pi(x,y) + \epsilon \text{KL}(\pi || \mathbb{P}_0 \times \mathbb{P}_1),
$$

where $\text{KL}(\pi || \mathbb{P}_0 \times \mathbb{P}_1)$ is the KL divergence between the distribution $\pi$ and the independent distribution $\mathbb{P}_0 \times \mathbb{P}_1$ with the marginals $\mathbb{P}_0$ and $\mathbb{P}_1$. In [Janati+2020] the authors consider the following problem:

$$
\min\_{\pi \in \Pi(\mathbb{P}\_0, \mathbb{P}\_1)} \int ||x-y||^2d\pi(x,y) + 2 \sigma^2 \text{KL}(\pi || \mathbb{P}_0 \times \mathbb{P}_1),
$$

which is equivalent to 

$$
\min\_{\pi \in \Pi(\mathbb{P}\_0, \mathbb{P}\_1)} \int \frac{||x-y||^2}{2}d\pi(x,y) + \sigma^2 \text{KL}(\pi || \mathbb{P}_0 \times \mathbb{P}_1).
$$

So $\sigma^2 = \epsilon$ as we use in our code.

**Comment by theouscidda6** [comment]
Thanks a lot for your quick answer and this clarification. I can close the issue.
